### ISSUE TITLE
Create install renpy sdk action

### ISSUE THREAD

**Issue by quillcraftsman** [ProjectAliceDev/renpy-build#10]
I've used `renpy-build-action` and `renpy-lint-action` in my project. It's good. Thanks!

In both actions first renpy sdk is installed. It's good then we use this actions separate. But this way have a side effects:
1. low speed
2. duplicated code

I propose to install `renpy` in the third separate action. In this way duplicated code will be removed and we can use this action separate. For example first install sdk then make lint than make build.

I will looks like:
```
   uses: ProjectAliceDev/renpy-install-action@master
   with:
       - some params
   uses: ProjectAliceDev/renpy-lint-action@master
   with:
       - some params
   uses: ProjectAliceDev/renpy-build-action@master
   with:
       - some params   
```

What do you think about it? Theoretically I can try to do refactoring myself If you will create the separate repository for new action, anyway I think it will be useful.
